User.destroy_all
Character.destroy_all
Test.destroy_all
Word.destroy_all

User.create(username: "test", email: "test@test.com", image: "http://fillmurray.com/200/300", password: "password", password_confirmation: "password")

Character.create([
  # Hiragana
  {symbol: 'あ', romaji: 'a'},
  {symbol: 'い', romaji: 'i'},
  {symbol: 'う', romaji: 'u'},
  {symbol: 'え', romaji: 'e'},
  {symbol: 'お', romaji: 'o'},
  {symbol: 'か', romaji: 'ka'},
  {symbol: 'き', romaji: 'ki'},
  {symbol: 'く', romaji: 'ku'},
  {symbol: 'け', romaji: 'ke'},
  {symbol: 'こ', romaji: 'ko'},
  {symbol: 'さ', romaji: 'sa'},
  {symbol: 'し', romaji: 'shi'},
  {symbol: 'す', romaji: 'su'},
  {symbol: 'せ', romaji: 'se'},
  {symbol: 'そ', romaji: 'so'},
  {symbol: 'た', romaji: 'ta'},
  {symbol: 'ち', romaji: 'chi'},
  {symbol: 'つ', romaji: 'tsu'},
  {symbol: 'て', romaji: 'te'},
  {symbol: 'と', romaji: 'to'},
  {symbol: 'な', romaji: 'na'},
  {symbol: 'に', romaji: 'ni'},
  {symbol: 'ぬ', romaji: 'nu'},
  {symbol: 'ね', romaji: 'ne'},
  {symbol: 'の', romaji: 'no'},
  {symbol: 'は', romaji: 'ha'},
  {symbol: 'ひ', romaji: 'hi'},
  {symbol: 'ふ', romaji: 'fu'},
  {symbol: 'へ', romaji: 'he'},
  {symbol: 'ほ', romaji: 'ho'},
  {symbol: 'ま', romaji: 'ma'},
  {symbol: 'み', romaji: 'mi'},
  {symbol: 'む', romaji: 'mu'},
  {symbol: 'め', romaji: 'me'},
  {symbol: 'も', romaji: 'mo'},
  {symbol: 'や', romaji: 'ya'},
  {symbol: 'ゆ', romaji: 'yu'},
  {symbol: 'よ', romaji: 'yo'},
  {symbol: 'ら', romaji: 'ra'},
  {symbol: 'り', romaji: 'ri'},
  {symbol: 'る', romaji: 'ru'},
  {symbol: 'れ', romaji: 're'},
  {symbol: 'ろ', romaji: 'ro'},
  {symbol: 'わ', romaji: 'wa'},
  {symbol: 'を', romaji: 'o'},
  {symbol: 'ん', romaji: 'n'},
  # Katakana
  {symbol: 'ア', romaji: 'a'},
  {symbol: 'イ', romaji: 'i'},
  {symbol: 'ウ', romaji: 'u'},
  {symbol: 'エ', romaji: 'e'},
  {symbol: 'オ', romaji: 'o'},
  {symbol: 'カ', romaji: 'ka'},
  {symbol: 'キ', romaji: 'ki'},
  {symbol: 'ク', romaji: 'ku'},
  {symbol: 'ケ', romaji: 'ke'},
  {symbol: 'コ', romaji: 'ko'},
  {symbol: 'サ', romaji: 'sa'},
  {symbol: 'シ', romaji: 'shi'},
  {symbol: 'ス', romaji: 'su'},
  {symbol: 'セ', romaji: 'se'},
  {symbol: 'ソ', romaji: 'so'},
  {symbol: 'タ', romaji: 'ta'},
  {symbol: 'チ', romaji: 'chi'},
  {symbol: 'ツ', romaji: 'tsu'},
  {symbol: 'テ', romaji: 'te'},
  {symbol: 'ト', romaji: 'to'},
  {symbol: 'ナ', romaji: 'na'},
  {symbol: 'ニ', romaji: 'ni'},
  {symbol: 'ヌ', romaji: 'nu'},
  {symbol: 'ネ', romaji: 'ne'},
  {symbol: 'ノ', romaji: 'no'},
  {symbol: 'ハ', romaji: 'ha'},
  {symbol: 'ヒ', romaji: 'hi'},
  {symbol: 'フ', romaji: 'fu'},
  {symbol: 'ヘ', romaji: 'he'},
  {symbol: 'ホ', romaji: 'ho'},
  {symbol: 'マ', romaji: 'ma'},
  {symbol: 'ミ', romaji: 'mi'},
  {symbol: 'ム', romaji: 'mu'},
  {symbol: 'メ', romaji: 'me'},
  {symbol: 'モ', romaji: 'mo'},
  {symbol: 'ヤ', romaji: 'ya'},
  {symbol: 'ユ', romaji: 'yu'},
  {symbol: 'ヨ', romaji: 'yo'},
  {symbol: 'ラ', romaji: 'ra'},
  {symbol: 'リ', romaji: 'ri'},
  {symbol: 'ル', romaji: 'ru'},
  {symbol: 'レ', romaji: 're'},
  {symbol: 'ロ', romaji: 'ro'},
  {symbol: 'ワ', romaji: 'wa'},
  {symbol: 'ヲ', romaji: 'o'},
  {symbol: 'ン', romaji: 'n'}
  ])

Word.create([
  # Words
  # Colors
  {symbol: 'あか', romaji: 'aka', meaning: 'red'},
  {symbol: 'あお', romaji: 'ao', meaning: 'blue'},
  {symbol: 'みどり', romaji: 'midori', meaning: 'green'},
  {symbol: 'くろ', romaji: 'kuro', meaning: 'black'},
  {symbol: 'しろ', romaji: 'shiro', meaning: 'white'},
  {symbol: 'きいろ', romaji: 'kiiro', meaning: 'yellow'},
  {symbol: 'ちゃいろ', romaji: 'cyairo', meaning: 'brown'},
  {symbol: 'むらさき', romaji: 'murasaki', meaning: 'purple'},
  {symbol: 'みずいろ', romaji: 'mizuiro', meaning: '?'},
  {symbol: 'きみどり', romaji: 'kimidori', meaning: '?'},
  # Greetings
  {symbol: 'おはよう',  romaji: 'ohayou', meaning: '?'},
  {symbol: 'こんにちは', romaji: 'konnnichiwa', meaning: '?'},
  {symbol: 'こんばんは', romaji: 'konbannwa', meaning: '?'},
  {symbol: 'さようなら', romaji: 'sayounara', meaning: '?'},
  {symbol: 'ありがとう', romaji: 'arigatou', meaning: '?'},
  {symbol: 'ごめんなさい', romaji: 'gomennnasai', meaning: '?'},
  {symbol: 'すみません', romaji: 'sumimasenn', meaning: '?'},
  {symbol: 'いただきます', romaji: 'itadakimasu', meaning: '?'},
  {symbol: 'ごちそうさまでした', romaji: 'gochisousamadeshita', meaning: '?'},
  {symbol: 'ようこそ', romaji: 'yokoso', meaning: '?'},
  # Foods
  {symbol: 'うどん', romaji: 'udon', meaning: '?'},
  {symbol: 'そば', romaji: 'soba', meaning: '?'},
  {symbol: 'ごはん', romaji: 'gohan', meaning: '?'},
  {symbol: 'てんぷら', romaji: 'tenpura', meaning: '?'},
  {symbol: 'すきやき', romaji: 'sukiyaki', meaning: '?'},
  {symbol: 'しゃぶしゃぶ', romaji: 'syabusyabu', meaning: '?'},
  {symbol: 'おでん', romaji: 'oden', meaning: '?'},
  {symbol: 'やきとり', romaji: 'yakitori', meaning: '?'},
  {symbol: 'どんぶり', romaji: 'donburi', meaning: '?'},
  {symbol: 'さしみ', romaji: 'sashimi', meaning: '?'},
  # Verbs
  {symbol: 'あるく', romaji: 'aruku', meaning: '?'},
  {symbol: 'はしる', romaji: 'hashiru', meaning: '?'},
  {symbol: 'すわる', romaji: 'suwaru', meaning: '?'},
  {symbol: 'たつ', romaji: 'tatsu', meaning: '?'},
  {symbol: 'ねむる', romaji: 'nemuru', meaning: '?'},
  {symbol: 'たべる', romaji: 'taberu', meaning: '?'},
  {symbol: 'のむ', romaji: 'nomu', meaning: '?'},
  {symbol: 'よむ', romaji: 'yomu', meaning: '?'},
  {symbol: 'みる', romaji: 'miru', meaning: '?'},
  {symbol: 'はなす', romaji: 'hanasu', meaning: '?'},
  # Verbs 2
  {symbol: 'もつ',  romaji: 'motsu', meaning: '?'},
  {symbol: 'まわす',  romaji: 'mawasu', meaning: '?'},
  {symbol: 'やすむ',  romaji: 'yasumu', meaning: '?'},
  {symbol: 'とまる',  romaji: 'tomaru', meaning: '?'},
  {symbol: 'おこる',  romaji: 'okoru', meaning: '?'},
  {symbol: 'する',  romaji: 'suru', meaning: '?'},
  {symbol: 'おきる',  romaji: 'okiru', meaning: '?'},
  {symbol: 'たたく',  romaji: 'tataku', meaning: '?'},
  {symbol: 'とる',  romaji: 'toru', meaning: '?'},
  {symbol: 'いく',  romaji: 'iku', meaning: '?'},
  # Time
  {symbol: 'きょう',  romaji: 'kyou', meaning: '?'},
  {symbol: 'きのう',  romaji: 'kinou', meaning: '?'},
  {symbol: 'あした',  romaji: 'ashita', meaning: '?'},
  {symbol: 'おととい',  romaji: 'ototoi', meaning: '?'},
  {symbol: 'あさって',  romaji: 'asatte', meaning: '?'},
  {symbol: 'あさ',  romaji: 'asa', meaning: '?'},
  {symbol: 'ひる',  romaji: 'hiru', meaning: '?'},
  {symbol: 'ゆうがた',  romaji: 'yuugata', meaning: '?'},
  {symbol: 'よる',  romaji: 'yoru', meaning: '?'},
  {symbol: 'よなか',  romaji: 'yonaka', meaning: '?'},
  # Jobs
  {symbol: 'しごと',  romaji: 'shigoto', meaning: '?'},
  {symbol: 'せんせい',  romaji: 'sensei', meaning: '?'},
  {symbol: 'がくせい',  romaji: 'gakusei', meaning: '?'},
  {symbol: 'かいしゃいん',  romaji: 'kaisyain', meaning: '?'},
  {symbol: 'いしゃ',  romaji: 'isya', meaning: '?'},
  {symbol: 'かんごし',  romaji: 'kangoshi', meaning: '?'},
  {symbol: 'だいく',  romaji: 'daiku', meaning: '?'},
  {symbol: 'しょうぼうし',  romaji: 'syouboushi', meaning: '?'},
  {symbol: 'りょうりにん',  romaji: 'ryourinin', meaning: '?'},
  {symbol: 'りきし',  romaji: 'rikishi', meaning: '?'},
  # City
  {symbol: 'とうきょう',  romaji: 'toukyou', meaning: '?'},
  {symbol: 'よこはま',  romaji: 'yokohama', meaning: '?'},
  {symbol: 'さっぽろ',  romaji: 'sapporo', meaning: '?'},
  {symbol: 'おおさか',  romaji: 'oosaka', meaning: '?'},
  {symbol: 'なごや',  romaji: 'nagoya', meaning: '?'},
  {symbol: 'おきなわ',  romaji: 'okinawa', meaning: '?'},
  {symbol: 'きょうと',  romaji: 'kyouto', meaning: '?'},
  {symbol: 'なら',  romaji: 'nara', meaning: '?'},
  {symbol: 'ちば',  romaji: 'chiba', meaning: '?'},
  {symbol: 'こうべ',  romaji: 'koube', meaning: '?'},
  # Vegetables
  {symbol: 'じゃがいも',  romaji: 'jyagaimo', meaning: '?'},
  {symbol: 'きゅうり',  romaji: 'kyuuri', meaning: '?'},
  {symbol: 'なす',  romaji: 'nasu', meaning: '?'},
  {symbol: 'たまねぎ',  romaji: 'tamanegi', meaning: '?'},
  {symbol: 'にんじん',  romaji: 'ninjin', meaning: '?'},
  {symbol: 'だいこん',  romaji: 'daikon', meaning: '?'},
  {symbol: 'はくさい',  romaji: 'hakusai', meaning: '?'},
  {symbol: 'かぶ',  romaji: 'kabu', meaning: '?'},
  {symbol: 'ごぼう',  romaji: 'gobou', meaning: '?'},
  {symbol: 'しょうが',  romaji: 'syouga', meaning: '?'},
  # Sushi
  {symbol: 'とろ',  romaji: 'toro', meaning: '?'},
  {symbol: 'ほたて',  romaji: 'hotate', meaning: '?'},
  {symbol: 'まぐろ',  romaji: 'maguro', meaning: '?'},
  {symbol: 'あじ',  romaji: 'aji', meaning: '?'},
  {symbol: 'いか',  romaji: 'ika', meaning: '?'},
  {symbol: 'うに',  romaji: 'uni', meaning: '?'},
  {symbol: 'たこ',  romaji: 'tako', meaning: '?'},
  {symbol: 'えんがわ',  romaji: 'engawa', meaning: '?'},
  {symbol: 'えび',  romaji: 'ebi', meaning: '?'},
  {symbol: 'たまご',  romaji: 'tamago', meaning: '?'},
  ])

Test.create([
  # Hiragana
  {name: "A", character_ids: [1,2,3,4,5]},
  {name: "KA", character_ids: [6,7,8,9,10]},
  {name: "SA", character_ids: [11,12,13,14,15]},
  {name: "TA", character_ids: [16,17,18,19,20]},
  {name: "NA", character_ids: [21,22,23,24,25]},
  {name: "HA", character_ids: [26,27,28,29,30]},
  {name: "MA", character_ids: [31,32,33,34,35]},
  {name: "YA", character_ids: [36,37,38]},
  {name: "RA", character_ids: [39,40,41,42,43]},
  {name: "WA", character_ids: [44,45,46]},
  {name: "All Hiragana", character_ids: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,
    41,42,43,44,45]},
  # Katakana
  {name: "A", character_ids: [47,48,49,50,51]},
  {name: "KA", character_ids: [52,53,54,55,56]},
  {name: "SA", character_ids: [57,58,59,60,61]},
  {name: "TA", character_ids: [62,63,64,65,66]},
  {name: "NA", character_ids: [67,68,69,70,71]},
  {name: "HA", character_ids: [72,73,74,75,76]},
  {name: "MA", character_ids: [77,78,79,80,81]},
  {name: "YA", character_ids: [82,83,84]},
  {name: "RA", character_ids: [85,86,87,88,89]},
  {name: "WA", character_ids: [90,91,92]},
  {name: "All Katakana", character_ids: [47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,
    89,90,91,92]},
    # Words
  {name: "Hiragana - Colors", word_ids: [1,2,3,4,5,6,7,8,9,10]},
  {name: "Hiragana - Greetings", word_ids: [11,12,13,14,15,16,17,18,19,20]},
  {name: "Hiragana - Foods", word_ids: [21,22,23,24,25,26,27,28,29,30]},
  {name: "Hiragana - Verbs", word_ids: [31,32,33,34,35,36,37,38,39,40]},
  {name: "Hiragana - Verbs 2", word_ids: [41,42,43,44,45,46,47,48,49,50]},
  {name: "Hiragana - Time", word_ids: [51,52,53,54,55,56,57,58,59,60]},
  {name: "Hiragana - Jobs", word_ids: [61,62,63,64,65,66,67,68,69,70]},
  {name: "Hiragana - City", word_ids: [71,72,73,74,75,76,77,78,79,80]},
  {name: "Hiragana - Vegetables", word_ids: [71,72,73,74,75,76,77,78,79,80]},
  {name: "Hiragana - Sushi", word_ids: [81,82,83,84,85,86,87,88,89,90]}
  ])
